services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - bankcards-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: bankcards-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankcards-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  bankcards-network:
    driver: bridge
